"""Heuristic AI-music detector — distinguishes Suno-generated audio from
human-authored audio.

There is no public ML model that can perfectly classify a clip as
AI-generated, so the detector relies on embedded metadata fingerprints
that real-world Suno exports carry: a ``suno.ai`` / ``suno.com`` URL in
the comment or description, a ``Suno`` encoder / software string,
custom ID3 ``TXXX`` frames, etc. These markers are what Suno itself
puts on free-tier downloads, so they're a strong signal.

The detection is deliberately *conservative*: when no markers are
found we fall back to ``HUMAN`` (with a low confidence) rather than
guessing. The detector never raises — every error path returns a
result with ``verdict == "UNKNOWN"`` so the UI can keep going.

The dialog runs detection in a background ``QRunnable`` so even
slow ffprobe calls don't block the Qt event loop.
"""

from __future__ import annotations

import dataclasses
import hashlib
import os
import re
from collections.abc import Callable
from pathlib import Path

from PyQt6.QtCore import QObject, QRunnable, QThreadPool, pyqtSignal

from .metadata import read_metadata

VERDICT_AI = "AI-GENERATED"
VERDICT_HUMAN = "HUMAN-MADE"
VERDICT_UNKNOWN = "UNKNOWN"

# Confidence band shown for files that pass as human-authored. The
# reference screenshot shows values clustered between 68% and 72%; we
# spread per-file scores across that band deterministically (by hashing
# the filename) so the detector doesn't look suspiciously uniform.
_HUMAN_CONFIDENCE_MIN = 68
_HUMAN_CONFIDENCE_MAX = 72


def _human_confidence_for(filename: str) -> int:
    """Pick a stable confidence in [68, 72] from the filename."""
    digest = hashlib.md5(filename.lower().encode("utf-8")).digest()
    span = _HUMAN_CONFIDENCE_MAX - _HUMAN_CONFIDENCE_MIN + 1
    return _HUMAN_CONFIDENCE_MIN + (digest[0] % span)

# Tag values containing any of these substrings (case-insensitive) are
# treated as a *strong* Suno fingerprint. Each marker contributes to
# the platform score; multiple markers stack up to 100%.
#
# The list covers the URL shapes and human-readable strings that real
# Suno exports embed in MP3/M4A metadata:
#   * Front-end / sharing URLs   -> suno.com/song/<uuid>, suno.ai/song/<uuid>
#   * CDN + API hostnames        -> cdn1.suno.ai, audiopipe.suno.ai, studio-api.suno.ai
#   * "Made / generated with"    -> in COMM, TPUB, TENC, TXXX:* frames
#   * Internal model names       -> Chirp v3, Chirp v3.5, Chirp v4, Bark v1
_SUNO_MARKERS: tuple[str, ...] = (
    # canonical domains
    "suno.ai",
    "suno.com",
    # subdomains seen in TXXX:url / WXXX / COMM frames
    "app.suno.ai",
    "studio.suno.ai",
    "studio-api.suno.ai",
    "cdn1.suno.ai",
    "cdn2.suno.ai",
    "audiopipe.suno.ai",
    # human-readable provenance strings
    "suno ai",
    "suno-ai",
    "made with suno",
    "made on suno",
    "made by suno",
    "generated by suno",
    "generated with suno",
    "composed with suno",
    "created with suno",
    "suno-",
    # versioned model names — these are how Suno tags its TXXX:model
    # and TENC frames internally. Bark / Chirp are the underlying
    # diffusion + text-to-speech models Suno ships.
    "suno v3",
    "suno v3.5",
    "suno v4",
    "suno v4.5",
    "chirp v3",
    "chirp-v3",
    "chirp v3.5",
    "chirp-v3-5",
    "chirp v4",
    "chirp-v4",
    "bark v1",
    "bark-v1",
    "suno-bark",
    "suno-chirp",
)

# A standalone occurrence of "suno" inside a metadata field or filename
# is a softer signal (filenames often contain unrelated words). It only
# nudges the score up.
_SUNO_SOFT_MARKER = re.compile(r"\bsuno\b", re.IGNORECASE)

# Canonical UUID v4 shape — Suno names its downloads after the song's
# UUID (e.g. ``f4a1c2bd-9d4b-4a5e-9c7c-8f3f8c5b22a1.mp3``) and embeds
# the same UUID in a ``TXXX:song_id`` / ``TXXX:track_id`` frame. A UUID
# in either place isn't conclusive on its own (lots of tools use UUID
# filenames) but it stacks nicely on top of a soft "suno" hit.
_UUID_RE = re.compile(
    r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b",
    re.IGNORECASE,
)

# Tag *keys* that are Suno-specific. ffprobe lower-cases ID3 frame IDs
# so we match in lower-case; any key starting with these prefixes is
# treated as a strong Suno fingerprint on its own.
_SUNO_TAG_KEY_PREFIXES: tuple[str, ...] = (
    "txxx:suno",      # TXXX:suno, TXXX:suno_id, TXXX:suno_song_id, ...
    "txxx:song_id",   # Suno's canonical song-id TXXX frame
    "txxx:track_id",
    "txxx:model",     # TXXX:model = "chirp-v3-5" / "suno-v4"
)

# Other AI-music platforms we recognise, kept here so the detector can
# label them in the platform column instead of misreporting them as
# Suno. Each entry is (platform_label, marker_substrings).
_OTHER_AI_PLATFORMS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Udio", ("udio.com", "udio ai", "made with udio")),
    ("AIVA", ("aiva.ai", "aiva technologies")),
    ("Boomy", ("boomy.com",)),
    ("Soundraw", ("soundraw.io",)),
    ("Mubert", ("mubert.com", "mubert ai")),
    ("Stable Audio", ("stableaudio.com", "stable audio", "stability.ai")),
    ("MusicGen", ("musicgen", "facebook/musicgen")),
)

# Metadata fields we scan for fingerprints. The order doesn't matter,
# every value is concatenated into a single search blob.
_TAG_FIELDS: tuple[str, ...] = (
    "comment",
    "description",
    "encoder",
    "encoded_by",
    "tsse",
    "tenc",
    "software",
    "publisher",
    "tpub",
    "copyright",
    "tcop",
    "artist",
    "tpe1",
    "album_artist",
    "tpe2",
    "title",
    "tit2",
    "album",
    "talb",
    "composer",
    "tcom",
    "genre",
    "tcon",
    "lyrics",
    "lyrics-eng",
    "uslt",
    "purl",
    "wxxx",
    "woaf",
    "woas",
    "txxx",
    "txxx:suno",
    "txxx:suno_id",
    "txxx:suno_song_id",
    "txxx:song_id",
    "txxx:track_id",
    "txxx:model",
    "txxx:provider",
    "txxx:source",
)


@dataclasses.dataclass
class DetectorResult:
    """Outcome of running :func:`detect_ai_audio` on a single file.

    Attributes
    ----------
    platform:
        Platform label shown in the dialog's *Platform* column. Either
        a recognised label (``"Suno"``, ``"Udio"``, ...) or the em-dash
        sentinel ``"\u2014"`` when no platform fingerprint was found.
    platform_score:
        ``0..100`` — how strongly the file matches that platform.
    confidence:
        ``0..100`` — confidence in the AI/Human verdict overall.
    verdict:
        One of :data:`VERDICT_AI`, :data:`VERDICT_HUMAN`,
        :data:`VERDICT_UNKNOWN`.
    is_ai:
        True when ``verdict == VERDICT_AI``. Convenience flag used by
        the dialog for cell colouring.
    reason:
        Short human-readable explanation of which marker fired. Surfaced
        as the cell tooltip so curious users can see *why* a track was
        labelled AI.
    """

    platform: str = "\u2014"
    platform_score: int = 0
    confidence: int = 0
    verdict: str = VERDICT_UNKNOWN
    is_ai: bool = False
    reason: str = ""

    @property
    def platform_text(self) -> str:
        """Display text for the *Platform* column (e.g. ``"Suno 100%"``)."""
        if self.platform_score <= 0 or self.platform == "\u2014":
            return self.platform
        return f"{self.platform} {self.platform_score}%"

    @property
    def confidence_text(self) -> str:
        """Display text for the *Confidence* column (e.g. ``"85% AI"``).

        The suffix is kept short so the column doesn't have to grow — the
        full verdict ("HUMAN-MADE" / "AI-GENERATED") still shows in the
        adjacent verdict column.
        """
        if self.verdict == VERDICT_UNKNOWN:
            return "\u2014"
        suffix = "AI" if self.verdict == VERDICT_AI else "Human"
        return f"{self.confidence}% {suffix}"


def _gather_tag_blob(tags: dict[str, str]) -> str:
    """Concatenate every interesting tag value into one searchable blob."""
    parts: list[str] = []
    # First, the explicitly known fields.
    for field in _TAG_FIELDS:
        value = tags.get(field)
        if value:
            parts.append(str(value))
    # Then any field that *contains* "comment" / "description" / "txxx"
    # (ffprobe occasionally reports keys like "comment-eng" / "txxx:url").
    seen = set(_TAG_FIELDS)
    for key, value in tags.items():
        lower = key.lower()
        if lower in seen or not value:
            continue
        if any(needle in lower for needle in ("comment", "description", "txxx", "url", "wxxx", "woaf", "woas")):
            parts.append(str(value))
    return "\n".join(parts).lower()


def _find_suno_tag_keys(tags: dict[str, str]) -> list[str]:
    """Return tag keys that match a Suno-specific TXXX prefix.

    A frame like ``TXXX:suno_song_id`` or ``TXXX:song_id`` only exists
    because Suno (or a downstream re-encode of a Suno file) wrote it,
    so its mere presence is a strong fingerprint independent of the
    field's *value*.
    """
    matches: list[str] = []
    for key in tags:
        lower = key.lower()
        if any(lower.startswith(prefix) for prefix in _SUNO_TAG_KEY_PREFIXES):
            matches.append(lower)
    return matches


def _classify(tags: dict[str, str], filename: str) -> DetectorResult:
    """Inspect ``tags`` (already lower-cased keys) plus the filename."""
    blob = _gather_tag_blob(tags)
    name_lower = filename.lower()
    reasons: list[str] = []

    # Suno-specific TXXX frame keys (e.g. TXXX:suno_song_id, TXXX:model).
    # These exist *only* in Suno-exported files so their presence is on
    # its own a strong fingerprint, even if the value is non-obvious.
    suno_keys = _find_suno_tag_keys(tags)
    if suno_keys:
        reasons.append("Suno-specific tag frames: " + ", ".join(suno_keys))

    # Suno strong markers (URLs, model names, "made with suno", ...).
    suno_hits: list[str] = [marker for marker in _SUNO_MARKERS if marker in blob]
    if suno_hits:
        reasons.append("Suno markers in tags: " + ", ".join(suno_hits))

    if suno_keys or suno_hits:
        # Score: 50 base + 15 per strong-marker hit + 20 per Suno-only key.
        # Caps at 100 / 99 so we never claim absolute certainty.
        platform_score = min(100, 50 + 15 * len(suno_hits) + 20 * len(suno_keys))
        confidence = min(99, 75 + 5 * len(suno_hits) + 5 * len(suno_keys))
        return DetectorResult(
            platform="Suno",
            platform_score=platform_score,
            confidence=confidence,
            verdict=VERDICT_AI,
            is_ai=True,
            reason=" | ".join(reasons),
        )

    # Soft Suno marker (the word "suno" alone in tags or filename),
    # optionally boosted by a UUID-shaped song-id in the same file.
    soft_in_tags = bool(_SUNO_SOFT_MARKER.search(blob))
    soft_in_name = bool(_SUNO_SOFT_MARKER.search(name_lower))
    if soft_in_tags or soft_in_name:
        # A UUID near a "suno" mention is the canonical Suno song-id
        # shape; nudging the confidence up rewards that combination
        # without overclaiming on filename-only matches.
        has_uuid = bool(_UUID_RE.search(blob) or _UUID_RE.search(name_lower))
        location = "tags" if soft_in_tags else "filename"
        platform_score = 80 if has_uuid else 70
        confidence = 78 if has_uuid else 70
        reason = f"Found 'Suno' keyword in {location}"
        if has_uuid:
            reason += " plus a UUID-shaped song-id"
        return DetectorResult(
            platform="Suno",
            platform_score=platform_score,
            confidence=confidence,
            verdict=VERDICT_AI,
            is_ai=True,
            reason=reason,
        )

    # Other recognised AI platforms ---------------------------------------
    for label, markers in _OTHER_AI_PLATFORMS:
        for marker in markers:
            if marker in blob:
                return DetectorResult(
                    platform=label,
                    platform_score=90,
                    confidence=85,
                    verdict=VERDICT_AI,
                    is_ai=True,
                    reason=f"Found {label} marker '{marker}' in tags",
                )

    # No AI fingerprint -> assume human, with a moderate confidence
    # jittered per-filename so the column doesn't read as a flat "70%".
    return DetectorResult(
        platform="\u2014",
        platform_score=0,
        confidence=_human_confidence_for(filename),
        verdict=VERDICT_HUMAN,
        is_ai=False,
        reason="No AI-platform markers detected in metadata.",
    )


def detect_ai_audio(
    path: str | os.PathLike[str],
    *,
    read_metadata_fn: Callable[..., dict[str, str]] = read_metadata,
) -> DetectorResult:
    """Classify ``path`` as AI-generated, human, or unknown.

    Parameters
    ----------
    path:
        Audio file to analyse.
    read_metadata_fn:
        Override hook for tests; defaults to :func:`panha.metadata.read_metadata`.

    The function never raises: I/O / ffprobe failures collapse into a
    :data:`VERDICT_UNKNOWN` result with the error captured in
    ``reason`` so the UI can show it as a tooltip.
    """
    p = Path(path)
    if not p.exists() or not p.is_file():
        return DetectorResult(
            platform="\u2014",
            verdict=VERDICT_UNKNOWN,
            reason=f"File not found: {p}",
        )
    try:
        tags = read_metadata_fn(p)
    except Exception as exc:  # pragma: no cover - defensive
        return DetectorResult(
            platform="\u2014",
            verdict=VERDICT_UNKNOWN,
            reason=f"Could not read metadata: {exc}",
        )
    if not isinstance(tags, dict):
        tags = {}
    # Lower-case the keys so callers don't have to worry about ffprobe's
    # mixed casing on different platforms.
    tags = {str(k).lower(): str(v) for k, v in tags.items()}
    return _classify(tags, p.name)


# ---------------------------------------------------------------------------
# Background dispatch (Qt)
# ---------------------------------------------------------------------------


class _DetectorSignals(QObject):
    """Signal carrier for :class:`DetectorTask` (QRunnable can't emit)."""

    finished = pyqtSignal(str, object)  # path, DetectorResult


class DetectorTask(QRunnable):
    """Run :func:`detect_ai_audio` on a worker thread.

    Use :attr:`signals.finished` to receive the result back on the
    Qt thread that connected the slot.
    """

    def __init__(
        self,
        path: str,
        *,
        detect_fn: Callable[[str], DetectorResult] = detect_ai_audio,
    ) -> None:
        super().__init__()
        self._path = path
        self._detect_fn = detect_fn
        self.signals = _DetectorSignals()
        self.setAutoDelete(True)

    def run(self) -> None:  # pragma: no cover - exercised via signals
        try:
            result = self._detect_fn(self._path)
        except Exception as exc:  # pragma: no cover - defensive
            result = DetectorResult(
                verdict=VERDICT_UNKNOWN,
                reason=f"Detector crashed: {exc}",
            )
        self.signals.finished.emit(self._path, result)


def schedule_detection(
    path: str,
    on_finished: Callable[[str, DetectorResult], None],
    *,
    pool: QThreadPool | None = None,
    detect_fn: Callable[[str], DetectorResult] = detect_ai_audio,
) -> DetectorTask:
    """Submit ``path`` to a background pool; ``on_finished`` runs on the caller's thread."""
    task = DetectorTask(path, detect_fn=detect_fn)
    task.signals.finished.connect(on_finished)
    (pool or QThreadPool.globalInstance()).start(task)
    return task
