"""Tests for the heuristic AI-music detector."""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("PyQt6")
from PyQt6.QtCore import QThreadPool  # noqa: E402
from PyQt6.QtWidgets import QApplication  # noqa: E402

from panha.detector import (  # noqa: E402
    VERDICT_AI,
    VERDICT_HUMAN,
    VERDICT_UNKNOWN,
    DetectorResult,
    detect_ai_audio,
    schedule_detection,
)


@pytest.fixture(scope="module")
def qapp():
    app = QApplication.instance() or QApplication([])
    yield app


# -- DetectorResult display helpers ------------------------------------


def test_result_display_for_ai_match():
    r = DetectorResult(
        platform="Suno",
        platform_score=100,
        confidence=85,
        verdict=VERDICT_AI,
        is_ai=True,
    )
    assert r.platform_text == "Suno 100%"
    assert r.confidence_text == "85% AI"


def test_result_display_for_human_match():
    r = DetectorResult(
        platform="\u2014",
        platform_score=0,
        confidence=70,
        verdict=VERDICT_HUMAN,
        is_ai=False,
    )
    # No platform fingerprint -> em-dash stays unchanged.
    assert r.platform_text == "\u2014"
    assert r.confidence_text == "70% Human"


def test_result_display_for_unknown_collapses_to_em_dash():
    assert DetectorResult().confidence_text == "\u2014"


# -- detect_ai_audio classifier ----------------------------------------


def test_detect_returns_unknown_for_missing_file(tmp_path: Path):
    result = detect_ai_audio(tmp_path / "ghost.mp3", read_metadata_fn=lambda *_a, **_k: {})
    assert result.verdict == VERDICT_UNKNOWN
    assert result.platform == "\u2014"
    assert "not found" in result.reason.lower()


def test_detect_flags_suno_url_in_comment(tmp_path: Path):
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"comment": "Made with Suno - https://suno.ai/song/abc"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.is_ai is True
    assert result.platform == "Suno"
    # Strong markers stack the platform score up to 100%.
    assert result.platform_score >= 80
    assert "suno" in result.reason.lower()


def test_detect_flags_suno_in_encoder_field(tmp_path: Path):
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"encoder": "Generated by Suno v3"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"


def test_detect_uses_filename_as_soft_fallback(tmp_path: Path):
    src = tmp_path / "Suno Track.mp3"
    src.write_bytes(b"")
    # No tags at all, but the filename mentions Suno.
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: {})
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"
    # Soft marker scores lower than a strong tag hit.
    assert result.platform_score < 90


def test_detect_classifies_clean_metadata_as_human(tmp_path: Path):
    src = tmp_path / "human.mp3"
    src.write_bytes(b"")
    tags = {"artist": "Joe Smith", "album": "Live At Home"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_HUMAN
    assert result.is_ai is False
    assert result.platform == "\u2014"


def test_detect_recognises_other_ai_platforms(tmp_path: Path):
    src = tmp_path / "udio.mp3"
    src.write_bytes(b"")
    tags = {"comment": "Created on udio.com"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Udio"


def test_detect_handles_non_dict_metadata(tmp_path: Path):
    """ffprobe occasionally returns garbage; the detector must not crash."""
    src = tmp_path / "weird.mp3"
    src.write_bytes(b"")
    result = detect_ai_audio(
        src, read_metadata_fn=lambda *_a, **_k: ["bogus", "list"]
    )
    # Falls through to the human/no-marker classifier without raising.
    assert result.verdict == VERDICT_HUMAN


def test_detect_is_case_insensitive(tmp_path: Path):
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"COMMENT": "VISIT SUNO.COM/SONG/123"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"


# -- background task ---------------------------------------------------


def test_schedule_detection_runs_off_thread_and_emits_result(
    qapp, tmp_path: Path
):
    pool = QThreadPool()
    pool.setMaxThreadCount(2)

    src = tmp_path / "song.mp3"
    src.write_bytes(b"")

    received: list[tuple[str, DetectorResult]] = []

    def fake_detect(_path: str) -> DetectorResult:
        return DetectorResult(
            platform="Suno", platform_score=95, confidence=90,
            verdict=VERDICT_AI, is_ai=True, reason="stubbed",
        )

    schedule_detection(
        str(src),
        lambda p, r: received.append((p, r)),
        pool=pool,
        detect_fn=fake_detect,
    )

    pool.waitForDone(5000)
    qapp.processEvents()

    assert len(received) == 1
    assert received[0][0] == str(src)
    assert received[0][1].is_ai is True
    assert received[0][1].platform == "Suno"


def test_dialog_apply_detection_result_renders_red_for_ai(qapp, tmp_path: Path):
    """Regression: dropping in a Suno-tagged file must end up showing the
    red 'AI-GENERATED' verdict in the table, not the analyzing
    placeholder."""
    from panha.dialogs.ai_detector_dialog import _COLOR_AI, AIDetectorDialog

    dlg = AIDetectorDialog(schedule_fn=lambda *a, **k: None)
    src = tmp_path / "suno_track.mp3"
    src.write_bytes(b"")
    assert dlg.add_paths([str(src)]) == 1

    dlg.apply_detection_result(
        0,
        DetectorResult(
            platform="Suno",
            platform_score=100,
            confidence=85,
            verdict=VERDICT_AI,
            is_ai=True,
            reason="Found Suno markers",
        ),
    )

    assert dlg.table.item(0, 1).text() == "Suno 100%"
    assert dlg.table.item(0, 2).text() == "85% AI"
    assert dlg.table.item(0, 3).text() == VERDICT_AI

    # Colour: AI cells must use the red AI palette.
    fg_brush = dlg.table.item(0, 3).foreground()
    assert fg_brush.color().rgb() == _COLOR_AI.rgb()
    # Verdict cell must render bold to match the screenshot.
    assert dlg.table.item(0, 3).font().bold() is True

    # Tooltip on the analysis cells surfaces the detector's reason so
    # users can click to see *why* a track was flagged.
    assert dlg.table.item(0, 3).toolTip() == "Found Suno markers"

    dlg.deleteLater()


def test_dialog_apply_detection_result_renders_green_for_human(
    qapp, tmp_path: Path
):
    from panha.dialogs.ai_detector_dialog import _COLOR_HUMAN, AIDetectorDialog

    dlg = AIDetectorDialog(schedule_fn=lambda *a, **k: None)
    src = tmp_path / "human.mp3"
    src.write_bytes(b"")
    assert dlg.add_paths([str(src)]) == 1

    dlg.apply_detection_result(
        0,
        DetectorResult(
            platform="\u2014", platform_score=0, confidence=72,
            verdict=VERDICT_HUMAN, is_ai=False,
        ),
    )

    assert dlg.table.item(0, 1).text() == "\u2014"
    assert dlg.table.item(0, 2).text() == "72% Human"
    assert dlg.table.item(0, 3).text() == VERDICT_HUMAN

    fg_brush = dlg.table.item(0, 3).foreground()
    assert fg_brush.color().rgb() == _COLOR_HUMAN.rgb()
    dlg.deleteLater()


def test_dialog_drag_drop_schedules_detection(qapp, tmp_path: Path):
    """Files dropped onto the dialog must be queued for detection."""
    from panha.dialogs.ai_detector_dialog import AIDetectorDialog

    scheduled: list[str] = []

    def fake_schedule(path, _on_finished, **_kwargs):
        scheduled.append(path)

    dlg = AIDetectorDialog(schedule_fn=fake_schedule)
    src = tmp_path / "drop.mp3"
    src.write_bytes(b"")
    dlg.add_paths([str(src)])

    assert scheduled == [str(src)]
    dlg.deleteLater()


# -- strengthened Suno detection --------------------------------------


def test_detect_flags_suno_studio_url(tmp_path: Path):
    """Suno's studio / API hostnames must also fingerprint as Suno."""
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"comment": "https://studio.suno.ai/song/abc"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"
    assert "studio.suno.ai" in result.reason.lower()


def test_detect_flags_suno_cdn_url(tmp_path: Path):
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"comment": "audio served from https://cdn1.suno.ai/xyz.mp3"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"


def test_detect_flags_suno_v4_model_string(tmp_path: Path):
    """``TXXX:model=Suno v4`` must be flagged even without a URL."""
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"txxx:model": "Suno v4"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"


def test_detect_flags_chirp_v3_model_string(tmp_path: Path):
    """Suno's internal Chirp model identifier counts as a Suno fingerprint."""
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"tenc": "chirp-v3-5"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"


def test_detect_flags_txxx_suno_key_even_without_suno_value(tmp_path: Path):
    """A Suno-only TXXX frame fingerprints the file regardless of value.

    Real Suno exports include frames like ``TXXX:suno_song_id`` that
    nothing else writes — their *presence* is what matters, not the
    UUID inside.
    """
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"txxx:suno_song_id": "f4a1c2bd-9d4b-4a5e-9c7c-8f3f8c5b22a1"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"
    assert "txxx:suno_song_id" in result.reason.lower()


def test_detect_flags_txxx_song_id_key(tmp_path: Path):
    """``TXXX:song_id`` (Suno's canonical key) fingerprints as Suno."""
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    tags = {"txxx:song_id": "f4a1c2bd-9d4b-4a5e-9c7c-8f3f8c5b22a1"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Suno"


def test_detect_soft_marker_with_uuid_boosts_confidence(tmp_path: Path):
    """A "suno" mention + UUID-shaped ID should outrank a bare keyword hit."""
    plain = tmp_path / "Suno Track.mp3"
    plain.write_bytes(b"")
    plain_result = detect_ai_audio(
        plain, read_metadata_fn=lambda *_a, **_k: {}
    )

    with_uuid = tmp_path / "Suno f4a1c2bd-9d4b-4a5e-9c7c-8f3f8c5b22a1.mp3"
    with_uuid.write_bytes(b"")
    uuid_result = detect_ai_audio(
        with_uuid, read_metadata_fn=lambda *_a, **_k: {}
    )

    assert plain_result.verdict == VERDICT_AI
    assert uuid_result.verdict == VERDICT_AI
    # The UUID nudge gives the second file a higher score than the
    # plain-keyword-only file.
    assert uuid_result.platform_score > plain_result.platform_score
    assert uuid_result.confidence > plain_result.confidence
    assert "uuid" in uuid_result.reason.lower()


def test_detect_stacks_multiple_suno_markers(tmp_path: Path):
    """Several strong markers should push the score higher than one alone."""
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    single = detect_ai_audio(
        src, read_metadata_fn=lambda *_a, **_k: {"comment": "https://suno.com/song/x"}
    )
    stacked = detect_ai_audio(
        src,
        read_metadata_fn=lambda *_a, **_k: {
            "comment": "https://suno.com/song/x",
            "tenc": "Suno v4",
            "tpub": "Suno AI",
        },
    )
    assert stacked.platform_score >= single.platform_score
    assert stacked.confidence >= single.confidence


def test_detect_recognises_stable_audio(tmp_path: Path):
    src = tmp_path / "stable.mp3"
    src.write_bytes(b"")
    tags = {"comment": "Generated by Stable Audio (stability.ai)"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Stable Audio"


def test_detect_recognises_mubert(tmp_path: Path):
    src = tmp_path / "mubert.mp3"
    src.write_bytes(b"")
    tags = {"comment": "Streamed via mubert.com"}
    result = detect_ai_audio(src, read_metadata_fn=lambda *_a, **_k: tags)
    assert result.verdict == VERDICT_AI
    assert result.platform == "Mubert"


# -- dialog: AI/Human verdict-string vocabulary -----------------------


def test_dialog_set_row_result_recognises_suno_ai_verdict_string(
    qapp, tmp_path: Path
):
    """``verdict="Suno AI"`` must light up the row as AI (red palette)."""
    from panha.dialogs.ai_detector_dialog import _COLOR_AI, AIDetectorDialog

    dlg = AIDetectorDialog(schedule_fn=lambda *a, **k: None)
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    dlg.add_paths([str(src)])

    dlg.set_row_result(0, platform="Suno", confidence="95%", verdict="Suno AI")

    row = dlg.rows()[0]
    assert row.is_ai is True
    fg = dlg.table.item(0, 3).foreground()
    assert fg.color().rgb() == _COLOR_AI.rgb()
    dlg.deleteLater()


def test_dialog_set_row_result_recognises_human_made_verdict_string(
    qapp, tmp_path: Path
):
    from panha.dialogs.ai_detector_dialog import _COLOR_HUMAN, AIDetectorDialog

    dlg = AIDetectorDialog(schedule_fn=lambda *a, **k: None)
    src = tmp_path / "track.mp3"
    src.write_bytes(b"")
    dlg.add_paths([str(src)])

    dlg.set_row_result(
        0, platform="\u2014", confidence="70%", verdict="HUMAN-MADE"
    )

    row = dlg.rows()[0]
    assert row.is_ai is False
    fg = dlg.table.item(0, 3).foreground()
    assert fg.color().rgb() == _COLOR_HUMAN.rgb()
    dlg.deleteLater()


def test_dialog_verdict_is_ai_falls_back_to_platform(qapp, tmp_path: Path):
    """An ambiguous verdict + a Suno platform label still resolves to AI."""
    from panha.dialogs.ai_detector_dialog import AIDetectorDialog

    assert AIDetectorDialog._verdict_is_ai("detected", platform="Suno 100%") is True
    assert AIDetectorDialog._verdict_is_ai("", platform="Udio 90%") is True
    assert AIDetectorDialog._verdict_is_ai("unsure", platform="\u2014") is False
